### ISSUE TITLE
y += x fails

### ISSUE THREAD

**Issue by bsxfan** [davidavdav/InplaceLinalg.jl#1]
```
julia> @macroexpand @inplace y += x
:(InplaceLinalg.C_AB!(y, 1, 1, nothing, x))
```

**Comment by bsxfan** [comment]
... but this does work:
```
julia> @macroexpand @inplace y = y + x
:(InplaceLinalg.C_AB!(y, 1, 1, 1, x))
```

**Comment by davidavdav** [comment]
Is that what you would like it to expand to? 

We should probably specify exactly what should expand to what, as in the to of [runtests.jl](https://github.com/davidavdav/InplaceLinalg.jl/blob/master/test/runtests.jl).  Also we might want to rename C_AB! to something like C_mul! or C_linear to describe more what we cover. 

The tests should also specify which expressions should err.  Currently you can probably write `C += B \ A`.

**Comment by bsxfan** [comment]
Thanks for the update. `y += x` works correctly now. But your other example is indeed a problem:
```
julia> @macroexpand @inplace C += A \ B
:(InplaceLinalg.C_AB!(C, 1, 1, 1, A \ B))
```
and
```
julia> @macroexpand @inplace C = C + A \ B
:(InplaceLinalg.C_AB!(C, 1, 1, 1, A \ B))
```

**Comment by bsxfan** [comment]
In related behaviour, compare some error messages I have added this morning:
```
julia> A = LowerTriangular(randn(2,2));B = randn(2,2); C = randn(2,2);
julia> @inplace C += A*B
ERROR: InplaceException: additive update to LHS not available for triangular multiplier (β==0 required).
``` 
and
```
julia> A,B = ntuple(i->randn(2,2),2);
julia> @inplace B = A*B
ERROR: InplaceException: multiplicative update to LHS not available for general multipliers.
```

**Comment by bsxfan** [comment]
Closed with[https://github.com/davidavdav/InplaceLinalg.jl/commit/059dc8d4f19ab4cd82e297c2bc7ee9e3a461799b](https://github.com/davidavdav/InplaceLinalg.jl/commit/059dc8d4f19ab4cd82e297c2bc7ee9e3a461799b). All of the cases mentioned in this issue now execute correctly.
